name: Photon Gallery
description: AJAX-powered gallery and photomanagement plugin for Croogo CMS

author: bumuckl (and Edinei L. Cipriani of course)
authorEmail: bumuckl@gmail.com
authorUrl: http://www.bumuckl.com